### ISSUE TITLE
Sketch Beta Version 3.4

### ISSUE THREAD

**Issue by pslanca** [zeplin/zeplin-sketch-plugin#5] opened 2015-10-09 15:40 UTC
Hey! Made the mistake of upgrading a sketch document to beta and just realised that the zeplin plugin is not compatible. Is there any way to export the artboards in beta? Thanks.

**Comment by merih** [comment] 2015-10-12 14:34
Hey @pslanca we're aware of the situation, but our hands are tied for this. We're in contact with the Sketch team and they said the issue is affecting a lot of plugins and they'll release an update to Sketch beta for this.

**Comment by bomberstudios** [comment] 2015-10-12 21:17
Here's an older beta, which should work with Zeplin and open your document just fine: https://www.dropbox.com/s/m0snmdnhwehrnkp/Sketch%20Beta%20%2815138%29.app.zip?dl=0

**Comment by berkcebi** [comment] 2015-10-12 21:20
Thanks a lot Ale! :)

**Comment by berkcebi** [comment] 2015-10-12 21:21
Oh and @bomberstudios, should we pass this along to other people asking as well?

**Comment by bomberstudios** [comment] 2015-10-23 07:08
Ah, sorry, missed your comment. The issue should be fixed by now (we released a new beta after that one) so you can close this : )

**Closed** 2015-10-23 10:40 UTC

**Comment by merih** [comment] 2015-10-23 10:42
Thanks @bomberstudios ! 🙋

**Comment by miyoun86** [comment] 2015-10-26 17:54
I just updated to Sketch 3.4 (non-beta), and the Zeplin plug-in is not working?
